"""
Annotation models for NousViz.

Annotations add human and contextual meaning to data —
algorithm updates, outages, campaign changes, analyst notes.
"""

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from enum import Enum
from typing import Optional


class AnnotationSource(Enum):
    MANUAL = "manual"       # User created via UI
    PLUGIN = "plugin"       # Generated by a plugin (e.g. "sync failed")
    ALERT = "alert"         # Created when an alert fires
    API = "api"             # Created via external API


class AnnotationCategory(Enum):
    NOTE = "note"                   # General note from analyst
    INCIDENT = "incident"           # Outage, downtime, tracking issue
    DEPLOYMENT = "deployment"       # New landing page, site change
    UPDATE = "update"               # Algorithm update, platform change
    CAMPAIGN = "campaign"           # Campaign started/paused/ended
    TERMS_CHANGE = "terms_change"   # Affiliate program changed terms


class AnnotationSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class Annotation:
    id: str
    title: str
    date_start: date
    source: AnnotationSource = AnnotationSource.MANUAL
    category: AnnotationCategory = AnnotationCategory.NOTE
    severity: AnnotationSeverity = AnnotationSeverity.INFO

    # Content
    description: Optional[str] = None
    color: Optional[str] = None

    # Scope
    plugin_id: Optional[str] = None
    dataset: Optional[str] = None
    date_end: Optional[date] = None
    scope_filters: dict = field(default_factory=dict)
    tags: list[str] = field(default_factory=list)

    # Lifecycle
    pinned: bool = False
    archived: bool = False
    created_by: str = "user"
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def is_range(self) -> bool:
        return self.date_end is not None and self.date_end != self.date_start

    @property
    def scope_label(self) -> str:
        if self.dataset:
            return f"{self.plugin_id or 'global'}/{self.dataset}"
        if self.plugin_id:
            return self.plugin_id
        return "global"

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "source": self.source.value,
            "category": self.category.value,
            "severity": self.severity.value,
            "color": self.color,
            "plugin_id": self.plugin_id,
            "dataset": self.dataset,
            "date_start": self.date_start.isoformat(),
            "date_end": self.date_end.isoformat() if self.date_end else None,
            "scope_filters": self.scope_filters,
            "tags": self.tags,
            "pinned": self.pinned,
            "archived": self.archived,
            "created_by": self.created_by,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "is_range": self.is_range,
            "scope_label": self.scope_label,
        }
